# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vxpu_pb2 as vxpu__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vxpu_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecutorStub:
    """Executor runs models shipped as vXPU artifacts: a content-addressed
    manifest (architecture config + weight references), weightless
    exported graphs, and a binding classifying every graph tensor as
    bound (weight reference), derived (computed from config), or state
    (session-owned, zero-initialized).

    The executor never receives weights over this API: it rehydrates
    them from the manifest's content-addressed references.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadModel = channel.unary_unary(
                '/vxpu.Executor/LoadModel',
                request_serializer=vxpu__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=vxpu__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.NewSession = channel.unary_unary(
                '/vxpu.Executor/NewSession',
                request_serializer=vxpu__pb2.NewSessionRequest.SerializeToString,
                response_deserializer=vxpu__pb2.NewSessionResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/vxpu.Executor/Chat',
                request_serializer=vxpu__pb2.ChatRequest.SerializeToString,
                response_deserializer=vxpu__pb2.ChatResponse.FromString,
                _registered_method=True)


class ExecutorServicer:
    """Executor runs models shipped as vXPU artifacts: a content-addressed
    manifest (architecture config + weight references), weightless
    exported graphs, and a binding classifying every graph tensor as
    bound (weight reference), derived (computed from config), or state
    (session-owned, zero-initialized).

    The executor never receives weights over this API: it rehydrates
    them from the manifest's content-addressed references.
    """

    def LoadModel(self, request, context):
        """LoadModel ships the artifact. Idempotent: the artifact's content
        digest identifies the model, and a matching digest reuses the
        already-loaded engine.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewSession(self, request, context):
        """NewSession allocates fresh per-session state (KV cache).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Chat runs one conversation turn in a session. Multi-turn reuses
        the session's cache: only new suffix tokens are prefilled.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=vxpu__pb2.LoadModelRequest.FromString,
                    response_serializer=vxpu__pb2.LoadModelResponse.SerializeToString,
            ),
            'NewSession': grpc.unary_unary_rpc_method_handler(
                    servicer.NewSession,
                    request_deserializer=vxpu__pb2.NewSessionRequest.FromString,
                    response_serializer=vxpu__pb2.NewSessionResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=vxpu__pb2.ChatRequest.FromString,
                    response_serializer=vxpu__pb2.ChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vxpu.Executor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vxpu.Executor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Executor:
    """Executor runs models shipped as vXPU artifacts: a content-addressed
    manifest (architecture config + weight references), weightless
    exported graphs, and a binding classifying every graph tensor as
    bound (weight reference), derived (computed from config), or state
    (session-owned, zero-initialized).

    The executor never receives weights over this API: it rehydrates
    them from the manifest's content-addressed references.
    """

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vxpu.Executor/LoadModel',
            vxpu__pb2.LoadModelRequest.SerializeToString,
            vxpu__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NewSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vxpu.Executor/NewSession',
            vxpu__pb2.NewSessionRequest.SerializeToString,
            vxpu__pb2.NewSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vxpu.Executor/Chat',
            vxpu__pb2.ChatRequest.SerializeToString,
            vxpu__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
